notification:
  email:
    on_success: never
    on_failure: never
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - lib32z1
      - lib32ncurses5
      - oracle-java8-installer
  sonarcloud:
    branches:
     - master
     - develop
    token:
      secure: $SONAR_TOKEN
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - "./gradlew --stacktrace -Pheadless=true check"
  - sonar-scanner
after_success:
  - "./gradlew distZip winZip createApp"
env:
  global:
    secure: IKl7OjpsYhATcjxY7zLJddJCfU0mo7tJ//ht8fl2l7/h6l+fduioSLzMWOXOpG5mTWILYS2dPvOzaJwFLN2KpxhYCCi9ogAw2a1NCa66pIEZUdBf5fnJy28HSolCWFe+RpDa6Q9id3tMY2Xie3Z+9LUbDPlEx5OXar7WCsjKu7Cm204Cs0vLSq5KaYcPPfIbCWhKQuTw7BM53hBWKBCrbFtRG2CAeg2LqNym1I4wKiz4Xeu7aXc4KxsWxYp4e6UToPfx6sPjR9xUaOi0wCbvJW9c7gqCkfdsXd/50lbRIjQSozyQJk4pH5O6Bngpd2bOJdxqd9Lj0Z5fAxN/kjn2jVTMEy91TiZOYRl4KALyJ5RYGFHIXOOLBFDgau5JDFKewjdVhK4lvoV37cLkAuzLdzHbU6sm2hm+7+2ovYlfKF8eO8JwXO4Eq9c5iv0hv1gEJAKyPja7YNNYiuFM3E1p+3CJy3d8VX9sIlwmdMGupy3qKlVvsZgqI1yYZOb4VqoOFAwtOCDR9f3xRaAG1joIsWhcPV40rDgYgzzcsEuzc6bJJEryT6t2DheVjEjSiMyYDYxfZ6iFpgx6kCzbBw7zjPF0xl3TQWVU22BiD9IPQVwjRoRyPCoQOCPwdMTl2BoMOuFF0hJrynLpczWj8lbp1zycRWyAdp2f1y7t+qDrcC8=
